# Generated by Django 4.2.17 on 2024-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('batch_number', models.CharField(max_length=100)),
            ],
        ),
    ]
